[package]
name = "webcom_ical"
version = "0.3.0"
edition = "2024"

[dependencies]
serde = { version = "1.0.219", features = ["derive"] }
reqwest = "0.12.15"
dotenvy = "0.15.7"
thirtyfour = "0.34.0"
tokio = { version = "1.44.2", features = ["full"] }
time = { version = "0.3.41", features = [
    "parsing",
    "macros",
    "formatting",
    "serde",
] }
kuma-client = "0.8.0"
url = "2.5.4"
icalendar = "0.16.13"
chrono = "0.4.40"
toml = "0.8.20"
serde_json = "1.0.140"
async-recursion = "1.1.1"
lettre = "0.11.15"
thiserror = "2.0.12"
strfmt = "0.2.4"
