[package]
name = "webcom_ical"
version = "0.3.0"
edition = "2021"

[dependencies]
serde = { version = "1.0.216", features = ["derive"] }
reqwest = "0.12.9"
dotenvy = "0.15.7"
thirtyfour = "0.34.0"
tokio = { version = "1.42", features = ["full"] }
time = { version = "0.3.37", features = [
    "parsing",
    "macros",
    "formatting",
    "serde",
] }
icalendar = "0.16.10"
chrono = "0.4.39"
toml = "0.8.19"
async-recursion = "1.1.1"
lettre = "0.11.11"
thiserror = "2.0.9"
strfmt = "0.2.4"
