[package]
name = "webcom_ical"
version = "0.1.0"
edition = "2021"

[dependencies]
dotenvy = "0.15.7"
thirtyfour = "0.34.0"
tokio = { version = "1", features = ["full"] }
time = { version = "0.3.36", features = ["parsing", "macros"] }
icalendar = "0.16.5"
chrono = "0.4.38"
chrono-tz = "0.9.0"
