[package]
name = "webcom_ical"
version = "0.3.0"
edition = "2021"

[dependencies]
serde = { version = "1.0.217", features = ["derive"] }
reqwest = "0.12.12"
dotenvy = "0.15.7"
thirtyfour = "0.34.0"
tokio = { version = "1.43.0", features = ["full"] }
time = { version = "0.3.37", features = [
    "parsing",
    "macros",
    "formatting",
    "serde",
] }
kuma-client = "0.8.0"
url = "2.5.4"
icalendar = "0.16.12"
chrono = "0.4.39"
toml = "0.8.20"
serde_json = "1.0.138"
async-recursion = "1.1.1"
lettre = "0.11.13"
thiserror = "2.0.11"
strfmt = "0.2.4"
