[package]
name = "webcom_ical"
version = "0.1.0"
edition = "2021"

[dependencies]
serde = { version = "1.0.210", features = ["derive"] }
dotenvy = "0.15.7"
thirtyfour = "0.34.0"
tokio = { version = "1", features = ["full"] }
time = { version = "0.3.36", features = [
    "parsing",
    "macros",
    "formatting",
    "serde",
] }
icalendar = "0.16.5"
chrono = "0.4.38"
toml = "0.8.19"
async-recursion = "1.1.1"
lettre = "0.11"
