name: webcom_${USERNAME}
services:
  webcom_ical:
    image: docker.io/library/webcom_ical
    volumes:
      - .env:/usr/src/webcom_ical/.env
      - {{save_target}}:/usr/src/webcom_ical/calendar/
      - ./kuma/:/usr/src/webcom_ical/kuma/
    environment:
      - RUST_LOG=warn
    restart: on-failure
