# playbook.yml
---
- name: Create new webcom ical
  hosts: servers
  vars_files:
      - group_vars/all.yml
  vars_prompt:
    - name: personeelsnummer
      prompt: "Voer personeelsnummer in"
      private: no

    - name: wachtwoord
      prompt: "Voer wachtwoord in"
      private: no
      
    - name: mail_to
      prompt: "Waar moet de email naartoe"
      private: no

    - name: timeout_time_hrs
      prompt: "How often should shifts be parsed"
      private: no
      default: "4"
      
    - name: new_shift
      prompt: "Mail on new shift (true/false)"
      private: no
      default: "true"

    - name: update_shift
      prompt: "Mail on updated shifts (true/false)"
      private: no
      default: "true"

  tasks:
    - name: Check if user exists
      ansible.builtin.stat:
        path: "~/Services/Webcom/{{ personeelsnummer }}"
      register: folder_stat

    - name: Fail if user exists
      ansible.builtin.fail:
        msg: "The user {{ personeelsnummer }} already exists."
      when: folder_stat.stat.exists

    - name: Generate a UUID
      set_fact:
        my_uuid: "{{ lookup('community.general.random_string', length=12, special=false, upper=false, digits=true, lower=true) }}"

    - name: Set environment variables
      set_fact:
        random_filename: "{{ my_uuid }}"

    - name: Set environment variables
      set_fact:
        timeout_time: "{{ timeout_time_hrs | int * 3600 + 400 }}"

    - name: Set cycle time
      set_fact:
        cycle_time: "{{ timeout_time_hrs | int * 3600}}"

    - name: Create user directory
      ansible.builtin.file:
        path: "~/Services/Webcom/{{ personeelsnummer }}"
        state: directory

    - name: Create .env file from template
      ansible.builtin.template:
        src: templates/env.j2
        dest: "~/Services/Webcom/{{ personeelsnummer }}/.env"

    - name: Create docker-compose.yml from template
      ansible.builtin.template:
        src: templates/docker-compose.yml.j2
        dest: "~/Services/Webcom/{{ personeelsnummer }}/docker-compose.yml"

    - name: Start Docker containers
      community.docker.docker_compose_v2:
       project_src: "~/Services/Webcom/{{ personeelsnummer }}"

    # - name: Add cron job to start Docker container every hour
    #   ansible.builtin.cron:
    #     name: "Start Docker container for {{ personeelsnummer }}"
    #     #user: "{{remote_username}}"
    #     minute: "{{59 | random}}"
    #     hour: "*/{{timeout_time_hrs}}"
    #     job: "docker start webcom_{{personeelsnummer}}-webcom_ical-1 >/dev/null 2>&1"
    #   when: remote_username != ""
