//! `SeaORM` Entity, @generated by sea-orm-codegen 2.0.0-rc.9

use sea_orm::entity::prelude::*;

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq)]
#[sea_orm(table_name = "donation_text")]
pub struct Model {
    #[sea_orm(primary_key)]
    pub id: i32,
    pub donate_link: String,
    pub donate_service_name: String,
    pub donate_text: String,
    pub iban: String,
    pub iban_name: String,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(has_many = "super::general_properties_db::Entity")]
    GeneralPropertiesDb,
}

impl Related<super::general_properties_db::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::GeneralPropertiesDb.def()
    }
}

impl ActiveModelBehavior for ActiveModel {}
