//! `SeaORM` Entity, @generated by sea-orm-codegen 2.0.0-rc.9

use sea_orm::entity::prelude::*;

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq)]
#[sea_orm(table_name = "email_properties")]
pub struct Model {
    #[sea_orm(primary_key)]
    pub id: i32,
    pub mail_from: String,
    pub smtp_server: String,
    pub smtp_username: String,
    pub smtp_password: String,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(has_many = "super::general_properties_db::Entity")]
    GeneralPropertiesDb,
    #[sea_orm(has_many = "super::kuma_properties::Entity")]
    KumaProperties,
}

impl Related<super::general_properties_db::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::GeneralPropertiesDb.def()
    }
}

impl Related<super::kuma_properties::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::KumaProperties.def()
    }
}

impl ActiveModelBehavior for ActiveModel {}
