//! `SeaORM` Entity, @generated by sea-orm-codegen 2.0.0-rc.9

use sea_orm::entity::prelude::*;

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq)]
#[sea_orm(table_name = "kuma_properties")]
pub struct Model {
    #[sea_orm(primary_key)]
    pub id: i32,
    pub domain: String,
    pub smtp_server: String,
    pub smtp_username: String,
    pub smtp_password: String,
    pub mail_from: String,
    pub mail_port: i32,
    pub use_ssl: bool,
    pub hearbeat_retry: i32,
    pub offline_mail_resend_hours: i32,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(has_many = "super::general_properties::Entity")]
    GeneralProperties,
}

impl Related<super::general_properties::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::GeneralProperties.def()
    }
}

impl ActiveModelBehavior for ActiveModel {}
