//! `SeaORM` Entity, @generated by sea-orm-codegen 2.0.0-rc.9

pub use super::donation_text::Entity as DonationText;
pub use super::email_properties::Entity as EmailProperties;
pub use super::general_properties_db::Entity as GeneralPropertiesDb;
pub use super::kuma_properties::Entity as KumaProperties;
